fix putAll implementation
qubole/caching-metastore-client pull request #15
Opened 2018-02-09 10:19 UTC by pvam

putAll implementation is broken. Changed implementation to appropriately use pipelines from https://github.com/xetorthio/jedis/wiki/AdvancedUsage.

Verified that putAll works now with arya metastore cache.

2018-02-11 13:35 UTC, vrajat requested changes
Is it possible to add UTs ?

2018-02-20 05:45 UTC, pvam commented
@vrajat have tested functionality with local jars, can add uts at a later point of time.

2018-02-20 12:24 UTC, vrajat approved these changes

2018-02-20 12:24 UTC, vrajat commented
OK. Go ahead. This requires some integration testing. Too hard with mocks which is the only option right now.

2018-02-22 10:45 UTC, merged