Issue 5
qubole/caching-metastore-client pull request #6
Opened 2017-12-08 09:13 UTC by sakshi2894

If a call to jedis getResource throws an exception we currently rethrow it.
Ideally we should make a best effort to put entires into cache and when we get a failure we should silently ignore cache errors.

if enableMissingCache is false, we should not put "not found" entries into cache.

2017-12-09 04:59 UTC, pvam commented
lgtm

2017-12-12 07:47 UTC, vrajat requested changes
I am guessing the goal here is to not throw an exception from get iff there is a problem using redis. In that case, the description of get looks like:
1. Get value from cache. If there is an exception, ignore and get from source client. Dont do anything else like put it in cache or put it in not found cache.
2. Cache does not have the value. I got it from source client. Now I have to either put it in cache or put it in not found. Do not throw an exception if you put or putnotfound fails. 

I dont think the code does this. I'll type in a better structure in a comment.

2017-12-12 07:54 UTC, vrajat commented
A better structure for get is:

    V v = null;
    bool cacheException = false;
    try {
        v = getIfPresent(key);
    catch (Throwable e) {
        bool cacheException = true;
     }

     if (v == null) {
        try {
            v = valueLoader.call();
             // Handle null
             if (cacheException = false) {
                  try {                 
                      this.put(key, v);
                  } catch (Throwable E) {
                      // Log error
                  }
             }
        } catch (Throwable E) { 
           // Add to missing cache and handle any exceptions from Jedis
       }

I know I am missing missing cache code. 

Definitely need unit tests :)

2017-12-19 16:20 UTC, vrajat requested changes
Basic tests look good. The only comment is that it is not checking the latest changes that put is not called if there is an exception in Jedis

2017-12-19 16:20 UTC, vrajat commented on src/test/java/com/qubole/utility/RedisCacheTest.java
> +    assert (valueExpected.equals(valueObserved));
Is it possible to check if put was not called since `cacheException` is true ?

2017-12-21 07:16 UTC, vrajat approved these changes

2017-12-21 07:18 UTC, merged